### PR TITLE
tii1q_b1 QPU runcard

### PR DESCRIPTION
**Pull request by aorgazf**
Dear All,
Please find a runcard for **tii1q_b1** qpu.
This processor belongs to the first batch fabricated by TII. It is installed at the XLD and controlled with Qblox Cluster and R&S local oscillator to drive the TWPA.

If you have not done it already, please ensure your environment has the latest version of pivisa-py and qblox-instruments 0.7.0:
```
pip install pyvisa-py
pip install qblox-instruments==0.7.0
```
The chip is installed in `reem2` node partition `tii1q_b1`.

My launching batch file looks like this:

```bash
#!/bin/bash

#SBATCH --job-name=qibocal_1q
#SBATCH --partition=tii1q_b1
#SBATCH --output=logs/latest_experiment_1q.log

qq ~/qibocal_1q.yml -o reports/$(date +'%Y%m%d')_latest_1q -f

```

Here are the fidelities measured with it:
image

Below some results obtained by @stavros11 :
```python
import qibo
from qibo import gates
from qibo.models import Circuit

qibo.set_backend("qibolab", platform="tii1q_b1")

c = Circuit(1)
c.add(gates.M(0))
result = c(nshots=5000)
print("Hardware frequencies:", result.frequencies())
# Hardware frequencies: Counter({'0': 4497, '1': 503})

c = Circuit(1)
c.add(gates.X(0))
c.add(gates.M(0))
result = c(nshots=5000)
print("Hardware frequencies:", result.frequencies())
# Hardware frequencies: Counter({'1': 4277, '0': 723})

c = Circuit(1)
c.add(gates.H(0))
c.add(gates.M(0))
result = c(nshots=5000)
print("Hardware frequencies:", result.frequencies())
# Hardware frequencies: Counter({'0': 2614, '1': 2386})
```

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by aorgazf** [comment]
Hi @scarrazza,
This PR is the same as PR #255, but pointing to main.

**Comment by scarrazza** [comment]
@stavros11 could you please confirm this is working for you?

**Comment by scarrazza** [comment]
@aorgazf #251 could be merged here at this point, right?

**Comment by stavros11** [comment]
> @stavros11 could you please confirm this is working for you?

Yes, it works including the shots. I think we can merge this.

> @aorgazf #251 could be merged here at this point, right?

Yes, I believe this requires to force `qblox-instruments==0.7.0` in order to work, so both should be merged at the same time.

**Review by stavros11 — APPROVED** [review]

**Comment by scarrazza** [comment]
Thanks @stavros11, I will merge #251 here and then this PR to main.

**Comment by aorgazf** [comment]
Thanks

**Pull request merged**
