### PR TITLE
0.2

### PR DESCRIPTION
**Pull request by alecandido**
Since we're now blocking features on 0.1, and we have a dedicated branch, https://github.com/qiboteam/qibolab/tree/0.1, it should be the proper time to make https://github.com/qiboteam/qibolab/tree/0.2 the actual `main` (i.e. the branch receiving new features).

### CODE REVIEW

**Comment by alecandido** [comment]
@stavros11 @hay-k just to be clear: I'm not requesting an actual review, all the content has already been reviewed before...

**Review by hay-k — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
I did a final test on hardware and the updated routines seem to work: http://login.qrccluster.com:9000/xLTo088LTjKn-W5Bnr5Pqw==

Of course, this doesn't cover everything we would like to do with qibolab 0.2, but hopefully we will be able to fix potential bugs in later releases without breaking the public interface.

@alecandido @scarrazza if you agree, we can merge this and release.

**Comment by alecandido** [comment]
> @alecandido @scarrazza if you agree, we can merge this and release.

I agree

**Comment by scarrazza** [comment]
Let me release qibo first and then update poetry before merging this.

**Comment by scarrazza** [comment]
@alecandido @stavros11 @hay-k thanks a lot for the great effort!

**Pull request merged**
