### PR TITLE
David/qubit flux track

### PR DESCRIPTION
**Pull request by DavidSarlle**
This PR updates the value of the "resonator_polycoef_flux" obtained from resonator espectroscopy flux (Qibocal PR https://github.com/qiboteam/qibocal/pull/487 )

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by aorgazf** [comment]
Could we find an alternative to `resonator_polycoef_flux`?
This name made sense when we were fitting a polynomial function to it, but now we are saving a series of parameters that are part of the analytical solution. @AlejandroSopena ? @igres26 ?

**Comment by DavidSarlle** [comment]
Hi @aorgazf, if I am not wrong, we are still saving the coefficients of a polynomical function. These are the optimal values obtained from curve_fit during the resonator flux fitting for the polynomical function "freq_r_trasmon" and "freq_r_matheu".

With these coefficients, we are able to estimate any resonator freq for a given bias during the qubit flux spec track resolving the previous functions used during the res spec fitting.

**Comment by DavidSarlle** [comment]
@aorgazf double checking the functions, you are right, they use a G_f_d function that is not polinomial. So, let me know (@AlejandroSopena @igres26 @aorgazf) the name that you want to use in the runcard for these parameters.

**Comment by AlejandroSopena** [comment]
I remember that `resonator_polycoef_flux` used to be a list of parameters to write the frequency as a polynomial of the flux, so these parameters did not really have physical meaning. Now, we need to store the new parameters in the runcard to track the resonator frequency and since each one has a physical meaning like `Ec`, `Ej` ... I suppose it is best to save each one separately in the runcard. As for the names, you can use the new names that appear in the flux routines' report (PR [#qibocal/486](https://github.com/qiboteam/qibocal/pull/486))

**Comment by DavidSarlle** [comment]
> I remember that `resonator_polycoef_flux` used to be a list of parameters to write the frequency as a polynomial of the flux, so these parameters did not really have physical meaning. Now, we need to store the new parameters in the runcard to track the resonator frequency and since each one has a physical meaning like `Ec`, `Ej` ... I suppose it is best to save each one separately in the runcard. As for the names, you can use the new names that appear in the flux routines' report (PR [#qibocal/486](https://github.com/qiboteam/qibocal/pull/486))

@AlejandroSopena what I am saving now in the runcard from the resonator spec flux are not all the fitted parameters in the routine (Ec, Ej, Xi...). From the fitted parameters, right now, we only save the ss and the res freq. the rest of the parameters are saved in the report but not in the runcard. With the new verion of the routine in qibocal PR 487, I am saving the optimal coeffients obtained for the "freq_r_trasmon" and "freq_mattheu" fitting. So, then, during the qubit flux track, we can use them to evaluate these functions for any given bias and set the resonator freq accordingly. 
@aorgazf is talking about the name of these coefficients, but as you said, they have no physical meaning, but also the they are not polynomical coefficients. So, I do not know what is the best name for storing them into the runcard.

**Comment by AlejandroSopena** [comment]
I think one option would be to replace the list `resonator_polycoef_flux` with a  dictionary `resonator_fitting_params` that will have 6 entries if the fit function is `freq_r_transmon` and 7 if `freq_r_mathieu` is used. This depends on whether we have initial values for Ec and Ej. Each key in the dictionary can be a descriptive name for the parameter, such as `{'bare_resonator_frequency':p0, 'readout_coupling':p1, 'sweetspot_0':p2, 'flux_to_bias':p3, 'asymmetry':p4, 'Ec':p5, 'Ej:p6'}` for `freq_r_mathieu`  and `{ 'sweetspot_0':p0, 'flux_to_bias':p1, 'asymmetry':p2, 'sweetspot_qubit_frequency/bare_resonator_frequency':p3, 'readout_coupling':p4, 'bare_resonator_frequency':p5}` for  `freq_r_transmon`

**Comment by DavidSarlle** [comment]
> 'bare_resonator_frequency'

@AlejandroSopena as we have spoken privatly, I will save in the runcard the missing parameters in the runcard obtained from the fitting, each one as a single qubit attribute. With that, we avoid the duplication of the parameters in the runcard (sweetspot, Ec, Ej, g, bare_resonator_freq...)

**Comment by DavidSarlle** [comment]
Closed for https://github.com/qiboteam/qibolab/tree/david/qubit_tracking

**Comment by DavidSarlle** [comment]
Closed for https://github.com/qiboteam/qibolab/tree/david/qubit_tracking

**Pull request closed without merging**
