### PR TITLE
Refactor IcarusQ instruments for multiqubit platform

### PR DESCRIPTION
**Pull request by sorewachigauyo**
This PR aims to refactor the IcarusQ instruments for use in the `MultiqubitPlatform` and remove the `ICPlatform`.

- [x] Refactor AWG Rack instruments code
- [x] Test AWG Rack operation
- [x] Refactor IcarusQ RFSoC code
- [x] Test IcarusQ RFSoC  operation
- [x] Remove `ICPlatform`
- [x] Write example notebooks for each runcard
- [x] Test platform on actual qubits

### CODE REVIEW

**Comment by scarrazza** [comment]
@sorewachigauyo thank you for waiting. Could you please try to merge here the latest main and see if everything still works?

**Comment by sorewachigauyo** [comment]
@scarrazza Sorry for the late reply, was on vacation
I have pulled the changes from main and made and tested the necessary changes on the instrument drivers. However, I have lost write access to this repo after accepting the qiboteam invite.

About the multiqubit platform (which seems to be leaning towards the default for this project), to add and use an instrument with the capability to play pulses, we need to [provide a `control` or `readout` role in the runcard](https://github.com/qiboteam/qibolab/blob/main/src/qibolab/platforms/multiqubit.py#L26-L29) and provide the following parameters [`channels`](https://github.com/qiboteam/qibolab/blob/main/src/qibolab/pulses.py#L1081-L1086) and `ports` 

`role` is used to identify if the instrument will be used to synthesize pulses and if measurement results are to be obtained from the instrument, `ports` is currently used by the Qblox instrument to modify certain instrument settings and `channels` is used by the `PulseSequence` object during execution to divide the sequence per each instrument.

Maybe we can instead expand the instrument abstraction to reflect and document the parameters and methods expected by the platform.

**Comment by sorewachigauyo** [comment]
> Please go ahead and propose the interface changes that are needed for your setup.

Currently the changes for the setup to work are implemented in this PR, so it should be good for review.

I feel that it is not very clear on the instrument side what is needed from the platform so I can try to draft a prototype in a separate PR and discuss with Alvaro when he is back from vacation.

**Comment by scarrazza** [comment]
@sorewachigauyo we are planning to merge code refactors that will remove runcards and the multiqubit platform.
Therefore we will remove the icarusq old files from main so you can readapt your platform from v0.0.5.

**Pull request closed without merging**
