### PR TITLE
Raise error on self-runner test

### PR DESCRIPTION
**Pull request by scarrazza**
Checklist:
- [x] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
Yes, I think this closes the issue.

Now that I see the test failing, however, I wonder if they should. The tests that are failing are not rfsoc/tii1q related... maybe in the future we could have more specific on hardware tests (?)

In any case, this is not important and at least now github pushes you to see if the tests are passing or not

**Comment by scarrazza** [comment]
Indeed, tests are crashing for erasynth (cc @maxhant).

**Comment by maxhant** [comment]
> Indeed, tests are crashing for erasynth (cc @maxhant).

It is fixed by #389

**Comment by scarrazza** [comment]
Thanks, let's merge.

**Pull request merged**
