### PR TITLE
Dummy without couplers

### LINKED ISSUE #645: Dummy without couplers
I have the impression that having another dummy without couplers may end up being useful for testing because most times we make a change in the couplers we break the non-coupler platforms.

### PR DESCRIPTION
**Pull request by stavros11**
Fixes #645. I had to put the couplers in all instruments `play` to unify their interface, that's why the files changed are more than expected.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by Jacfomg — APPROVED** [review]
Thanks, looks good !

**Review by andrea-pasquale — APPROVED** [review]
Thanks @stavros11 for implementing this. I think it goes into the right direction.
Only one question: regarding testing protocols in qibocal what should we do now?
I guess that the naive option would to test everything with `dummy_couplers` .
A second option could be to split the protocols to be tested into the ones the support couplers and the ones that do not support them. Let me know what do you think (also since qibocal installs the stable of qibolab we will face this problem only around december)

**Comment by stavros11** [comment]
Thank you for reviewing.

> Thanks @stavros11 for implementing this. I think it goes into the right direction. Only one question: regarding testing protocols in qibocal what should we do now? I guess that the naive option would to test everything with `dummy_couplers` . A second option could be to split the protocols to be tested into the ones the support couplers and the ones that do not support them. Let me know what do you think (also since qibocal installs the stable of qibolab we will face this problem only around december)

Ideally we should test all protocols with both dummies, except ofcourse the ones that only work with couplers which should be tested only with `dummy_couplers`. The goal is to avoid issues where introducing couplers to a routine breaks it for non-coupler platforms, like it happened with the chevron, so testing only with `dummy_couplers` is not sufficient for this. My only concern if we test with two dummies is the execution times for tests, because I noticed that both qibolab and qibocal tests are a bit slow. Maybe we could improve something inside the dummy instrument, or just use less shots and sweep points.

**Comment by stavros11** [comment]
I pushed a small fix for the dummy, because the loop over readout pulses was being done twice while we only need it once. I do not see any other straightforward way to speed up tests so I will merge this as it is for now.

**Comment by andrea-pasquale** [comment]
> Ideally we should test all protocols with both dummies, except of course the ones that only work with couplers which should be tested only with `dummy_couplers`. The goal is to avoid issues where introducing couplers to a routine breaks it for non-coupler platforms, like it happened with the chevron, so testing only with `dummy_couplers` is not sufficient for this. My only concern if we test with two dummies is the execution times for tests, because I noticed that both qibolab and qibocal tests are a bit slow. Maybe we could improve something inside the dummy instrument, or just use less shots and sweep points.

Thanks for clarifying. I also noted that qibocal tests are quite slow. We already tried to reduce the number of shots and the swept points. I don't know what else we should do to speed them up.

**Pull request merged**
