### PR TITLE
Update laboneq

### PR DESCRIPTION
**Pull request by Jacfomg**
Update laboneq to a compatible version for the firmware update.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by scarrazza** [comment]
@Jacfomg, I have updated reem1 and reem2, could you please retry this PR?

**Comment by Jacfomg** [comment]
Okay, this PR works to install the correct version, but still I need to change to https://github.com/qiboteam/qibolab/pull/575 ti run things as something broke that I fixed there.

**Review by AleCandido — APPROVED** [review]
This one is tiny and good on its own, I would even merge immediately.

The only drawback is that we won't be able to release Qibolab until #508. Only for this reason, it might be worth to wait for it.

**Review by stavros11 — APPROVED** [review]
I have not tested myself but I trust it works.

> The only drawback is that we won't be able to release Qibolab until #508. Only for this reason, it might be worth to wait for it.

Regarding the release, I would consider including #585 because it is needed in qibocal and #587 that is bug fix, but of course we can also have multiple releases close to each other.

**Comment by Jacfomg** [comment]
> I have not tested myself but I trust it works.
> 
> > The only drawback is that we won't be able to release Qibolab until #508. Only for this reason, it might be worth to wait for it.
> 
> Regarding the release, I would consider including #585 because it is needed in qibocal and #587 that is bug fix, but of course we can also have multiple releases close to each other.

@GabrielePalazzo and @DavidSarlle also confirm it works. Feel free to merge when it's more convinient.

**Comment by scarrazza** [comment]
@AleCandido @stavros11 @Jacfomg may I ask you to include those in the next [milestone](https://github.com/qiboteam/qibolab/milestone/6)?

**Pull request merged**
