### PR TITLE
Drop symbolic expressions

### PR DESCRIPTION
**Pull request by AleCandido**
I thought I dropped symbolic.py in #709, but I was wrong (sorry @hay-k). Here I am doing what I forgot to do there (since all the references were already removed in that PR).

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Thanks. There is a leftover reference to symbolic but in a comment
https://github.com/qiboteam/qibolab/blob/9c6a5ec7de2c0de347f1b56298da43bd54275e2a/tests/test_pulses.py#L79

**Review by hay-k — APPROVED** [review]

**Comment by AleCandido** [comment]
My bad, I forgot to grep case-insensitive.

However, I'm surprised that everything is passing, since there are still a bunch of mentions I forgot:
```py
❯ rg '\bse_'
src/qibolab/pulses.py
1026:        # def __init__(self, start:int | se_int, duration:int | se_int, amplitude:float, frequency:int, relative_phase:float, shape: PulseShape | str,
1083:        # def __init__(self, start:int | se_int, duration:int | se_int, amplitude:float, frequency:int, relative_phase:float, shape: PulseShape | str,
1113:        # def __init__(self, start:int | se_int, duration:int | se_int, amplitude:float, frequency:int, relative_phase:float, shape: PulseShape | str,

tests/test_instruments_zhinst.py
379:            duration=ro_pulses[qubit].se_start,

tests/test_instruments_qmsim.py
443:            start=y90_pulse.se_finish,
451:            lowfreq, start=flux_pulse.se_finish, relative_phase=np.pi / 3
454:            highfreq, start=flux_pulse.se_finish, relative_phase=0
458:            lowfreq, start=y90_pulse.se_finish, relative_phase=np.pi / 3
461:            highfreq, start=x_pulse_start.se_finish, relative_phase=0
465:        lowfreq, start=theta_pulse.se_finish
468:        highfreq, start=x_pulse_end.se_finish
```

**Comment by stavros11** [comment]
> However, I'm surprised that everything is passing, since there are still a bunch of mentions I forgot:

From qmsim tests, they require specific options to be passed in the `pytest` command so they are not executed in the CI. Btw, I'm planning to drop these tests (possibly in one of the QM PRs).

For the Zurich test, it's a bit weird that it didn't fail. It is not marked as qpu so it should not be skipped. Maybe that's worth investigating.

**Comment by AleCandido** [comment]
That test is actually skipped, I just checked. I'm trying to understand why.

**Comment by AleCandido** [comment]
I found it:
https://github.com/qiboteam/qibolab/blob/0765763ffc14feef40fbdb6a726bf1b24f594fba/tests/test_instruments_zhinst.py#L231
https://github.com/qiboteam/qibolab/blob/0765763ffc14feef40fbdb6a726bf1b24f594fba/tests/test_instruments_zhinst.py#L355
https://github.com/qiboteam/qibolab/blob/0765763ffc14feef40fbdb6a726bf1b24f594fba/tests/test_instruments_zhinst.py#L764

**Comment by AleCandido** [comment]
I'd rather avoid fixing that problem in this PR, since it's not related to symbolic at all. If you agree @stavros11, I'd just merge (feel free to do it yourself).

**Pull request merged**
