### PR TITLE
TWPA extra

### LINKED ISSUE #961: TWPA extra
We should add an alias for the TWPA dependency. Now, they need the LO extra
https://github.com/qiboteam/qibolab/blob/4f1459444a88666bad3b360dd728b0b88fa9c366/pyproject.toml#L91

(alias = copy-pasting that line, and call it `twpa`)

### PR DESCRIPTION
**Pull request by alecandido**
Closes #961 

It was easier to do it immediately, instead of leaving a further issue open and forget.

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Okay, but I still don't see how this is any useful given that if someone knows how to do `pip install .[twpa]` they could just as well do `pip install .[los]`. The missing piece is documentation.

**Comment by alecandido** [comment]
> Okay, but I still don't see how this is any useful given that if someone knows how to do `pip install .[twpa]` they could just as well do `pip install .[los]`. The missing piece is documentation.

Ah, yes, definitely.

This is not useful on its own, just "clearer". I.e., if you need a TWPA, but not an LO, then you could use `pip install .[twpa]`, instead of `pip install .[los]`, when you don't have LOs.

But the relevant one is certainly https://github.com/qiboteam/qibolab_platforms_qrc/issues/163

**Comment by stavros11** [comment]
> This is not useful on its own, just "clearer". I.e., if you need a TWPA, but not an LO, then you could use `pip install .[twpa]`, instead of `pip install .[los]`, when you don't have LOs.

Strictly speaking, qibolab is not controlling the TWPA itself but the TWPA pump, which in all cases so far it happens to actually be an LO. :) (no issues with merging this though, fortunately it is not causing any conflicts)

**Comment by alecandido** [comment]
> Strictly speaking, qibolab is not controlling the TWPA itself but the TWPA pump, which in all cases so far it happens to actually be an LO. :) (no issues with merging this though, fortunately it is not causing any conflicts)

Ok, this is formally correct, but slightly less intuitive.

To be fair, both `los` and `twpa` are a bit out of the usual scheme. Indeed, we don't have extras for `controller`, so we may separate by vendor, and possibly specific product.

However, we are not really at the level of being that *strict* on this, and even `los` is not that bad. It was just confusing me.
But, if this is worse, we could even revert.

**Pull request merged**
