### PR TITLE
Bug fix in qblox multiqubit platform affecting multiplexed readout

### PR DESCRIPTION
**Pull request by aorgazf**
This PR fixes the issue #329 Multiplex not working for QBlox, for all routines except for the precision scans of the spectroscopies. 
The precision scans are going to be removed in qibocal https://github.com/qiboteam/qibocal/pull/270, soon, until then, one can comment out the precision sections of the resonator and qubit spectroscopies.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by DavidSarlle** [comment]
@aorgazf thanks for fixing the bug so quickly. It works for me.

**Review by andrea-pasquale — APPROVED** [review]

**Review by scarrazza — APPROVED** [review]

**Comment by scarrazza** [comment]
@Simone-Bordoni are you familiar with the failed test?

**Comment by Simone-Bordoni** [comment]
@scarrazza in the tests random circuits are employed, the test fails if there are not at least two 2-qubit gates. This happens with a really low probability so re-running tests will solve the problem. Anyway next week i will open a PR for some improvements of the transpiler and i will also fix this

**Comment by scarrazza** [comment]
@Simone-Bordoni sorry but don't get it, why these tests are not using a fixed and reproducible random seed?

**Comment by Simone-Bordoni** [comment]
@scarrazza i forgot to add the seed, corrected in #338

**Pull request merged**
