### PR TITLE
Replace YAML runcard with JSON ones

### LINKED ISSUE #762: Drop `yaml` dependency
Of course, PyYAML is only used to serialize the runcard. However, this can well be used just in the `create()` methods (if ever, we could even use something else).

This is definitely not urgent, but having less dependencies in Qibolab will make it easier to deploy.

### PR DESCRIPTION
**Pull request by alecandido**
Closes #762

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
Looks good to me. I would just ask @scarrazza if he agrees with the change, because historically we were using json and he proposed moving to yaml (I am guessing for readability?).

**Comment by scarrazza** [comment]
It is fine by me, supposing json will reduce complexity in terms of dependencies.

**Comment by stavros11** [comment]
@andrea-pasquale @alecandido I spoke with @aorgazf and he also agrees with this change, so if this is ready we can merge and I will propagate the changes to qibolab_platforms_qrc.

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale @alecandido I spoke with @aorgazf and he also agrees with this change, so if this is ready we can merge and I will propagate the changes to qibolab_platforms_qrc.

Good, @stavros11 I might have the majority of the JSON ready for `qibolab_platform_qrc`. I can take of that if you want.

**Comment by alecandido** [comment]
@stavros11 now it is merged. It will be anyhow in the next release, so no need to rush for the changes in the `qibolab_platforms_qrc` (for as long as people will use the latest release, of course it will be required for testing new PRs in Qibolab)

**Comment by stavros11** [comment]
> Good, @stavros11 I might have the majority of the JSON ready for `qibolab_platform_qrc`. I can take of that if you want.

Thanks, if you already have them feel free to open a PR. Otherwise I will do it later or tomorrow.

> @stavros11 now it is merged. It will be anyhow in the next release, so no need to rush for the changes in the `qibolab_platforms_qrc` (for as long as people will use the latest release, of course it will be required for testing new PRs in Qibolab)

I am not sure if there is anyone (other than qibocal CI) that is using releases, but in any case it will be useful to have at least a PR with the json runcards to be able to keep developing on qibolab main.

**Comment by alecandido** [comment]
I believe Qibocal should usually develop against releases, and only sometimes using the Git version (when a new Qibolab feature is strictly required).

**Comment by alecandido** [comment]
> This is why usually I push for qibolab releases 😄

I know, this is the unpleasant part, and the motivation for monorepos. However, hopefully it will happen less and less :)

**Pull request merged**
