### PR TITLE
Fix QPU tests

### PR DESCRIPTION
**Pull request by stavros11**
Updates the mechanism for QPU tests (`-m qpu`). Now the tests/dummy_qrc platforms are used for non-qpu tests, while the platforms in qibolab_platforms_qrc are used for qpu tests.

In order to run non-qpu tests you simply do
```py
pytest
```
while for qpu tests the queue and the platform (from qibolab_platforms_qrc) needs to be specified
```py
srun -p tii1q_b1 pytest -m qpu --platforms tii1q_b1 --no-cov
```
This requires prior setting of the [`QIBOLAB_PLATFORMS` environment flag](https://github.com/qiboteam/qibolab_platforms_qrc#readme), so that the runcards can be loaded It will execute the qpu tests on all instruments that are available in the given platform. If an instrument is not available, its tests will be skipped.

I have tested this on qw5q_gold_qblox and tii1q_b1. Some rfsoc tests are failing but these should be fixed by #532.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
Merging this PR in #532 worked and I was able to run the tests (actually not on the tii1q_b1 but my for my fault, the server on the rfsoc4x2 has a patch now running).
`srun -p tii1q_b1 pytest -m qpu --platforms tii_zcu111 --no-cov`

However I still got some errors related to other qpu test:
```
=========================== short test summary info ============================
FAILED tests/test_platforms_abstract.py::test_platform_execute_empty[platform0]
FAILED tests/test_platforms_abstract.py::test_platform_execute_one_drive_pulse[platform0]
FAILED tests/test_platforms_abstract.py::test_multiqubitplatform_execute_one_long_drive_pulse[platform0]
FAILED tests/test_platforms_abstract.py::test_multiqubitplatform_execute_one_extralong_drive_pulse[platform0]
FAILED tests/test_platforms_abstract.py::test_multiqubitplatform_execute_multiple_readout_pulses[platform0]
= 5 failed, 32 passed, 33 skipped, 2232 deselected, 12 xfailed, 15 warnings in 83.89s (0:01:23) =
```

**Comment by stavros11** [comment]
Tests with QPU are passing on QM and qblox. Since qblox is ready, I suggest merging this as it is and we can check Zurich and rfsoc tests when it is on main. I will also work on recovering the qpu workflow with labels then.

**Comment by rodolfocarobene** [comment]
Thanks @stavros11, I fully agree

**Review by rodolfocarobene — APPROVED** [review]

**Comment by scarrazza** [comment]
Thanks @stavros11.

**Pull request merged**
