### PR TITLE
Initial support for binning

### PR DESCRIPTION
**Pull request by aorgazf**
Hi,
This PR introduces an initial support for *binning*. Up until now, the execution of a sequence of pulses for a determined number of iterations (`nshots`), returned the average of all of those measurements.
With this PR the result of each shot can be retrieved independently using:
 ```python
platform.execute_pulse_sequence(exc_sequence, nshots)['shots'][ro_pulse.serial]
```
or just to retrieve the last set for a particular qubit:
 ```python
platform.execute_pulse_sequence(exc_sequence, nshots)['shots'][qubit]`
```
Below is an example:
```python
    from qibolab import Platform
    from qibolab.paths import qibolab_folder
    from qibolab.pulses import PulseSequence
	
    # Define platform and load specific runcard
    runcard = qibolab_folder / "runcards" / "tii5q.yml"
    platform = Platform("tii1q", runcard)

    # Connects to lab instruments using the details specified in the calibration settings.
    platform.connect()
    platform.setup()
    platform.start()
	
    platform.qrm[qubit].ports['i1'].hardware_demod_en = True # binning only works with hardware demodulation enabled
    # create exc sequence
    exc_sequence = PulseSequence()
    RX_pulse = platform.create_RX_pulse(qubit, start=0)
    ro_pulse = platform.create_qubit_readout_pulse(qubit, start=RX_pulse.duration)
    exc_sequence.add(RX_pulse)
    exc_sequence.add(ro_pulse)
    nshots=1204
    shots_results = platform.execute_pulse_sequence(exc_sequence, nshots)['shots'][ro_pulse.serial]
    for n in np.arange(nshots):
        msr, phase, i, q = shots_results[n]
        results = {
            "MSR[V]": msr,
            "i[V]": i,
            "q[V]": q,
            "phase[rad]": phase,
            "iteration[dimensionless]": n,
        }
        print(results)
    # Turn off lab instruments
    platform.stop()
    # Disconnect from the instruments
    platform.disconnect()
```

### CODE REVIEW

**Comment by stavros11** [comment]
@aorgazf after merging main (which contains David's runcard for tii5q) to this branch the i-q values still differ, eg. for qubit 2:

with hardware demodulation I get:
gnd: -0.0013065012212994628-0.0015348155715681486j
exc: -0.0015863955300439668-0.0036059667806546164j

with software demodulation I get:
gnd: -0.0013739698874256389-0.0010242416368002542j
exc: -0.0021237652423943005-0.0028317662690749107j

Is this expected? Moreover the shots are not very well seperated in the i-q plane.

In order to merge this we need:
* Make sure that we are getting consistent results with and without hardware demodulation (if this is what should happen).
* Get well seperated clouds for at least one qubit.
* Tests should pass.

**Comment by DavidSarlle** [comment]
I have tested this PR and it is compatible with qibocal/main. Also the last runcard commited  from @aorgazf in this branch works and is getting similar results from soft and hardware demodulation for qubit 2.

Software:
    
image


Hardware:
            state0_voltage: 7982
            state1_voltage: 13880
            mean_gnd_states: (-0.003592833071262824-0.007128100001526624j)
            mean_exc_states: (-0.005331567537860283-0.012815620992611139j)

**Comment by stavros11** [comment]
Thanks @DavidSarlle. I confirm these values up to (not small) variations, maybe due to noise/shift (?). Note that the values of mean_gnd_states/mean_exc_states in the runcard are the ones we get with hardware demodulation on, however this is set to false. Shouldn't we change this to true so that binning also works? Also, is it expected that the i, q values are different when the modulation is done on software or hardware?

Regarding binning, I get a not very clear seperation for qubit 2:
shots
Are you getting a better result? Here is the code I used:
<details>
<summary>Code</summary>

```py
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
from qibolab import Platform
from qibolab.pulses import Pulse, PulseSequence, ReadoutPulse

platform = Platform("tii5q")
qubit = 2


platform.connect()
platform.setup()
platform.start()

ro_pulse = platform.create_MZ_pulse(qubit, start=0)
sequence = PulseSequence()
sequence.add(ro_pulse)
result0 = platform.execute_pulse_sequence(sequence, nshots=10000)


qd_pulse = platform.create_RX_pulse(qubit)
ro_pulse = platform.create_MZ_pulse(qubit, start=qd_pulse.duration)
sequence = PulseSequence()
sequence.add(qd_pulse)
sequence.add(ro_pulse)
result1 = platform.execute_pulse_sequence(sequence, nshots=10000)

platform.stop()
platform.disconnect()

print("Ground state:", result0.get(qubit))
print("Excited state:", result1.get(qubit))

if "binned_integrated" in result0:
    shots0 = np.array(result0.get("binned_integrated").get(qubit))
    shots1 = np.array(result1.get("binned_integrated").get(qubit))

    plt.scatter(shots0[:, 2], shots0[:, 3], color="blue", label="gnd")
    plt.scatter(shots1[:, 2], shots1[:, 3], color="red", label="exc", alpha=0.5)
    plt.xlabel("i")
    plt.ylabel("q")
    plt.savefig("shots.png")
```

</details>

**Comment by stavros11** [comment]
> @aorgazf had to recalculate qubit states becasue the relative phase was set to 0 in qibolab main after he characterized and commit the changes of the initial runcard pushed.

Regarding the ro_pulse phase, this was a quick fix to make the voltages independent of the readout start time, because otherwise it was not possible to get correct probabilities especially when doing gates. If you have a better solution please propose this, as long as it does not break the probability calculation.

**Comment by DavidSarlle** [comment]
@stavros11 Using the latest runcard, and the branches qibocal/fast_calibrate_qubit_states_pr and qibolab/faster_fidelity_pr, wich contains the latest improvemts from the point of view of execution velocity and are compatible between them, I obtain the following resuts executing "calibrate_qubit_states" and "calibrate_qubit_states_binning" wich are using soft and hw demodulation respectively:

image

image

These results are more than acceptable, I would say and the differences between them are also acceptable.

**Comment by DavidSarlle** [comment]
@stavros11 also, as you pointed in your comment about the HW demod enabled or not. You are right. As the results obtained fromusing HW demod or soft demod are not the same and we have done the calibration of the qubit states with the HW demod enabled, we should set to true the hardware_demod_en of the qrm_rf in the runcard, at least until we have fixed the problem that is causing the differences (if possible).

Also, could be a problem, the fact that we have calibrated all the pi pulses using soft modulation and demodulation, and it could be a source of problems. I think we should first see if we can solve the differences between soft and hw mod/demod, and then decide if the best option to be the default in the runcard (taht is going to be the HW because is faster). 

Said that. If you enable the qrm_rf hw demod and you use the latest values of voltages for state0 and 1 in my previous comment, you obtain the following probabilities for allXY and qubit2:

image

**Comment by DavidSarlle** [comment]
And if you use the current in the runcard values for voltages state0 and 1 withh the qrm_rf HW demod = false you obtain the following probabilities:

image

I think we should double check if all the params in the runcard has been updated using soft or hw demod and recalibrate. Afterthat, check if we are obtaining different results and fix the bug (if possible)

**Comment by stavros11** [comment]
Thanks @DavidSarlle, I can reproduce the plots. however I noticed that increasing the number of shots makes the clouds a bit more mixed

Screenshot from 2022-10-17 00-56-01

Let me propose to start cleaning up the PRs related to binning:
* Ideally we would like to merge #192 here, however it is pointing to #177. Therefore you need to decide with @maxhant if you will keep the fidelity function from #177 in qibolab. At this point I think it is easier to keep it because it will be a bit messy if we try to merge #192 directly here.
* Merge #192 to #177 and then everything here. Note that the runcard in #192 is outdated so you will have conflicts when you try to merge. You should keep the latest runcard.
* Merge #193, which I believe is the latest runcard, here.

At this stage having these multiple PRs open makes sense only if someone else is planning to review all the changes line by line, or if you are not sure about the implementation in one of the above mentioned PRs. If everything works for you I would suggest to merge it here so that we have a single branch with acceptable probabilities and binning which is easier for everyone to test. Then we test this and if everything is working we merge to main. @scarrazza let me know if you agree.

**Comment by aorgazf** [comment]
Thank you @stavros11 for your feedback and for your support to get these PRs merged.

> Ideally we would like to merge https://github.com/qiboteam/qibolab/pull/192 here, however it is pointing to https://github.com/qiboteam/qibolab/pull/177.

Regarding that, I think the functionality can always be removed, (replaced by a function in qibocal) so, in the absence of a decision about this disagreement, I will merge the PRs as suggested and resolve the conflicts.

**Comment by aorgazf** [comment]
> Thanks @DavidSarlle, I can reproduce the plots. however I noticed that increasing the number of shots makes the clouds a bit more mixed

This is expected. As far as I understand the voltages corresponding to 0 or 1 are Gaussian distributions. The more points you probe, the more you will find away from the mean. However, the fidelity should not change if the fridge is not heating up as a result of the execution (which is something we have not studied thoroughly).

**Comment by aorgazf** [comment]
@scarrazza has confirmed his approval to proceed with the suggested merges

**Comment by stavros11** [comment]
Thanks @aorgazf, everything works for me after the merges, including the qblox classification. Here are some data for reference:
<details>
<summary>5000 shots</summary>

shotsfull_5000

Qubit (State) | Shots | p0 | shots0 / nshots 
-- | -- | -- | -- 
1 (gnd) | [4479  521] | 1.0143 | 0.8958
1 (exc) | [ 710 4290] | 0.05676 | 0.1420
2 (gnd) | [4408  592] | 0.9348 | 0.8816
2 (exc) | [ 847 4153] | 0.09991 | 0.1694
3 (gnd) | [4802  198] | 1.00297 | 0.9604
3 (exc) | [ 363 4637] | 0.05917 | 0.0726
4 (gnd) | [4803  197] | 0.9985 | 0.9606
4 (exc) | [ 593 4407] | 0.06649 | 0.1186

</details>
<details>
<summary>20000 shots</summary>

shotsfull_20000

Qubit (State) | Shots | p0 | shots0 / nshots
-- | -- | -- | -- 
1 (gnd) | [14409  5591] | 0.79992 | 0.72045
1 (exc) | [ 2476 17524] | 0.01921 | 0.1238
2 (gnd) | [18664  1336] | 1.09378 | 0.9332
2 (exc) | [ 2945 17055] | 0.05444 | 0.14725
3 (gnd) | [19367   633] | 0.99429 | 0.96835
3 (exc) | [ 1727 18273] | 0.02675 | 0.08635
4 (gnd) | [19148   852] | 0.99191 | 0.9574
4 (exc) | [ 2289 17711] | 0.03733 | 0.11445

</details>

I believe the numbers look as expected so from my side this PR can be merged to main. The only blocking issue that we should resolve before merging is the tests failing on qpu.

Another thing that we should check is how is the classification performing when we excite the qubit with multiple drive pulses, not a single RX as we do now, because this will be the case when using gates.

FYI: I am working on another branch on top of this that updates the measurement gates following qiboteam/qibo#647. Measurement gates will be part of the queue. I will also implement the `result.samples()` and `result.frequencies()` functionality for acquiring the classified shots after executing a circuit, in order to be symmetric to simulation.

**Comment by stavros11** [comment]
@aorgazf the following script
```py
platform = Platform("tii5q")

platform.connect()
platform.setup()
platform.start()

ro_pulse1 = platform.create_MZ_pulse(1, start=0)
ro_pulse2 = platform.create_MZ_pulse(2, start=ro_pulse1.duration)
sequence = PulseSequence()
sequence.add(ro_pulse1)
sequence.add(ro_pulse2)

results = platform.execute_pulse_sequence(sequence, nshots=5000)

platform.stop()
platform.disconnect()
```
fails with
```
Traceback (most recent call last):
  File "/nfs/users/stavros.efthymiou/qibolab/debug.py", line 19, in <module>
    results = platform.execute_pulse_sequence(sequence, nshots=5000)
  File "/nfs/users/stavros.efthymiou/qibolab/src/qibolab/platforms/multiqubit.py", line 41, in execute_pulse_sequence
    acquisition_results.update(self.instruments[name].play_sequence_and_acquire())
  File "/nfs/users/stavros.efthymiou/qibolab/src/qibolab/instruments/qblox.py", line 997, in play_sequence_and_acquire
    i, q = self._process_acquisition_results(raw_results[acquisition_name], pulse, demodulate=True)
TypeError: cannot unpack non-iterable numpy.float64 object
```
Particularly the `self._process_acquisition_results` method returns `nan`.

**Comment by aorgazf** [comment]
I believe I have already fixed the issues highlighted by @stavros11 and @andrea-pasquale. I have managed to run T1s on two qubits simultaneously. 
Remaining subtasks:
- [ ] carry out some more tests and confirm everything works.
- [ ] fix tests and amend documentation.

**Pull request merged**
