### PR TITLE
Adding flux pulse creation in the platform

### PR DESCRIPTION
**Pull request by GabrielePalazzo**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by stavros11** [comment]
> @stavros11 since we mentioned the option of dropping all the `Platform.create_*` methods, should we close this one?

I guess it is still not clear if we will drop (or change) `Platform.create_*` methods, but in any case this will be discussed as part of the 0.2 refactor. For now, I do not mind even merging this and we can update/remove together with the rest later.

My only concern regarding the new method in particular is that, unlike `create_RX_pulse` and `create_MZ_pulse` (the native gates), the new one does not read any infromation from the platform. Instead the user is supposed to pass everything (duration, amplitude) as arguments. Therefore, I am not sure what we gain by having it under `Platform`, given that the user is still free to define flux pulses using the pulse API directly (with minimal overhead compared to calling this method). For that maybe @GabrielePalazzo has some arguments. I believe it was needed for some routine in qibocal.

**Comment by alecandido** [comment]
> I guess it is still not clear if we will drop (or change) `Platform.create_*` methods, but in any case this will be discussed as part of the 0.2 refactor. For now, I do not mind even merging this and we can update/remove together with the rest later.

Ok, even fine merging. I would just avoid keeping this in a limbo, and since it was draft it would have been easier to close.
But both closing and merging are fine (while keeping it stale is not great...).

**Comment by GabrielePalazzo** [comment]
> Therefore, I am not sure what we gain by having it under `Platform`, given that the user is still free to define flux pulses using the pulse API directly (with minimal usability overhead compared to calling this method). For that maybe @GabrielePalazzo has some arguments. I believe it was needed for some routine in qibocal.

Yes, the only reason why I added the `create_` method here was to avoid defining the exact same pulse in different qibocal routines.

**Review by alecandido — APPROVED** [review]
For as long as we keep the `create_` methods (most likely until 0.2.0) it is fine to have this in `main`.

**Review by stavros11 — APPROVED** [review]
I agree, feel free to merge if it's working with the qibocal routine.

**Pull request merged**
