### PR TITLE
qw5q_gold runcard as of 20230331 12:00

### PR DESCRIPTION
**Pull request by aorgazf**
This PR includes the latest characterisation of qw5q_gold QPU.
To use it please refer to the qrccluster wiki
All 5 qubits seem to be working although q4 readout requires further work. I would then recommend using qubits q0 - q4.

q0, q2 and q3 have assignment fidelities above 0.9

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Coverage does not decrease.

### CODE REVIEW

**Comment by scarrazza** [comment]
@MatteoRobbiati could you please give a try?

**Comment by stavros11** [comment]
> I am using the last version of qibolab: `0.0.3dev0` in edit mode activating this branch. I run a simple test example and I got this:
> 
> ```
> RuntimeError: Cannot establish connection to <qibolab.instruments.rohde_schwarz.SGS100A object at 0x7f7199153250> instruments. Error captured: 'InstrumentException with SGS100A@192.168.0.32: Unable to connect to lo_drive_low'
> ```
> 
> Can you tell me @aorgazf if it can be expected or I set up something wrong?

@MatteoRobbiati the versions of the dependencies, in this case qblox-instruments, qcodes and pyvisa-py, should be exactly the same with those stated in setup.py. This is because the instrument firmware only works with specific library versions.

**Review by andrea-pasquale — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
Currently this branch is not working given that it doesn't contain some fixes, like #335, which were added in main, and people are starting from this branch to implement other features.
Given that everybody is using this runcard I suggest to merge this branch asap to main, so that people don't find old bugs.
@scarrazza @stavros11 @aorgazf @DavidSarlle let me know if you agree.

**Comment by scarrazza** [comment]
Please go ahead.

**Comment by andrea-pasquale** [comment]
> Please go ahead.

In Qibolab I cannot merge without two approving reviews.

**Pull request merged**
