### PR TITLE
Introduce crosstalk_matrix as `Qubit` attribute

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Required by https://github.com/qiboteam/qibocal/pull/684.

When it will get merged I will also update accordingly qibolab_platforms.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by AleCandido** [comment]
Are you sure it should go under each single qubit? It should be a matrix in the first place, rotating from all qubits (a weight for each one) to all qubits.

Wouldn't it be more appropriate to put it under a qubits container?
It could be the `QubitMap`, but it's potentially better to keep that simple (`id: Qubit`) and hold this information directly in the `Platform`.

**Comment by andrea-pasquale** [comment]
> Are you sure it should go under each single qubit? It should be a matrix in the first place, rotating from all qubits (a weight for each one) to all qubits.
> 
> Wouldn't it be more appropriate to put it under a qubits container? It could be the `QubitMap`, but it's potentially better to keep that simple (`id: Qubit`) and hold this information directly in the `Platform`.

The current approach is the first thing that came to my mind. Indeed, it should a be a matrix. I am not really sure about putting it under a `qubits` container. Mainly because I don't want to overcomplicate the runcard if necessary. A possible solution could be to put a row of the matrix under each qubit (similarly to what I am doing with the only difference that instead of storing it as a dict we store directly as an array). 

Also regardless of how we store it, we can add a method to the platform which generates directly the crosstalk matrix.

**Comment by AleCandido** [comment]
> Also regardless of how we store it, we can add a method to the platform which generates directly the crosstalk matrix.

But it's going to be used altogether anyhow, and it makes connections between multiple qubits. If there is going to be a method in the platform, we could well put the whole attribute there.

**Review by stavros11 — APPROVED** [review]
Following the meeting, we decided to merge this now and refactor later (if needed) when implementing the mechanism for flux corrections.

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
