### PR TITLE
Keysight M8195A AWG

### PR DESCRIPTION
**Pull request by Rezahekmati**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

P.S.: I mistakenly push this update initially to the main branch, then I revert it. Please ignore that!

### CODE REVIEW

**Comment by scarrazza** [comment]
Hello @Rezahekmati, may I ask you a short description of the platform you are planning to support? Thank you.

**Comment by Rezahekmati** [comment]
Hello @scarrazza Initially I had defect systems (like diamond or silicon) and quantum dots (III-V) in mind; however, I would like to extend it to neutral atoms, rare earth ions, trapped ions, and superconducting qubits (which your paper is about). Hardware wise, M8195A can be used in most of all these platforms to the best of my knowledge (if not all). Thank you.

**Comment by scarrazza** [comment]
@Rezahekmati, we don't have access to this set of instruments in our labs, therefore in order to consider this PR you have to fix the failing checks, make sure tests are passing and coverage is preserved.

**Comment by Rezahekmati** [comment]
Dear @scarrazza Thanks. I resolved the issues and now, I can see "All checks have passed". However, for "Review required" and "Merging is blocked", I think someone with write access should work on these two items. Please let me know if something needs to be done from myside. Thanks

**Comment by scarrazza** [comment]
@Rezahekmati as mentioned, please make sure all tests are passing (linter, pytest, coverage, docs). At the moment this not seem the case, please check https://github.com/qiboteam/qibolab/actions/runs/8550387959/job/23427289537?pr=823

**Comment by scarrazza** [comment]
@Rezahekmati, thanks for syncing the fork and merging main, closing and reopening the PR is not working, therefore let's close this PR and later, when you are done with drivers, you can open another PR based on a new branch.

**Comment by Rezahekmati** [comment]
No problem @scarrazza and sorry for my slow reply. Thanks for the guidance. Now, I'll close my PR and work on my code.

**Pull request closed without merging**
