### PR TITLE
Re-calibration tii1q_b1

### PR DESCRIPTION
**Pull request by rodolfocarobene**
This branch contains the latest version of the tii1q_b1 runcard

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Thanks @rodolfocarobene.
I pushed here the fix for the classification and the updated runcard generated with the autocalibration script.

**Comment by andrea-pasquale** [comment]
I still need to fix tests, however the runcard should already be usable.

**Review by andrea-pasquale — APPROVED** [review]
Now the runcard is calibrated with the fidelity above 90%

**Comment by andrea-pasquale** [comment]
@stavros11 @scarrazza @AleCandido  I tried to run tests on the board using the label but tests are failing due to [poetry](https://github.com/qiboteam/qibolab/actions/runs/4794559215/jobs/8528076991?pr=379). Do you have any ideas on how to fix it?

**Comment by AleCandido** [comment]
> @stavros11 @scarrazza @AleCandido I tried to run tests on the board using the label but tests are failing due to [poetry](https://github.com/qiboteam/qibolab/actions/runs/4794559215/jobs/8528076991?pr=379). Do you have any ideas on how to fix it?

The problem with Poetry is just that is absent from the runner.
```
/nfs/users/github/actions-runner/_work/_temp/6c72f4c2-28c8-4065-80f5-cb7e3f389557.sh: line 4: poetry: command not found
```
https://github.com/qiboteam/qibolab/actions/runs/4794559215/jobs/8528076991?pr=379#step:5:28

So, either add Poetry installation in the workflow itself, with one of the many methods available (possibly the recommended one),
https://github.com/qiboteam/qibolab/blob/9990d0faaff18483d74a9fb30a062d0fbfd56e62/.github/workflows/selfhosted.yml#L43-L57
or simply install Poetry on the runner.

I guess before was installed, and now it is not any longer.

**Comment by andrea-pasquale** [comment]
Thanks @AleCandido.
@scarrazza which of the 2 options do you recommend?

**Comment by scarrazza** [comment]
@andrea-pasquale option 2, I have just installed poetry on the runner workspace, please give a try.

**Comment by andrea-pasquale** [comment]
Same issue with poetry again 
https://github.com/qiboteam/qibolab/actions/runs/4795252611/jobs/8529583966?pr=379

**Comment by scarrazza** [comment]
Ok, the good news is that now runners are isolated from the OS dependencies. 
The bad news is that we have to update the workflow recipe to install all requirements.

**Comment by andrea-pasquale** [comment]
> Ok, the good news is that now runners are isolated from the OS dependencies. The bad news is that we have to update the workflow recipe to install all requirements.

I see. Thanks for checking.

**Pull request merged**
