### PR TITLE
qw5q_gold runcard 20230413 8:00am

### PR DESCRIPTION
**Pull request by aorgazf**
image
image
image
image
image
image
image
image
image
image

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]
Thanks @aorgazf.
LGTM.
Just one question, why now we have `hardware_mod_en` set to `True`?

**Comment by DavidSarlle** [comment]
@aorgazf is this runcard the latest for qw5q_gold? I am calibrating the q2 using autocalibration and I am getting different values. Some of them are sligthtly different (and it's fine) but for example the sweetspot is quite different to the one that is in this runcard.
The runcard has a sweetspot for q2 = -0.167 and I am getting something near -0.325 or -0.33

**Comment by DavidSarlle** [comment]
@aorgazf forget my last comment. There ws a bug in the qubit flux dependence method introduced in the autocalibration. Now it is fixed. Sorry.

**Comment by aorgazf** [comment]
> Thanks @aorgazf. LGTM. Just one question, why now we have `hardware_mod_en` set to `True`?

Hi, @andrea-pasquale , there was no need to change that in this PR, but since I was working on sweepers and in order to make use of frequency sweepers, the pulse needs to be modulated in hardware, I had change it to hardware modulation.
In the next version of the driver, this is going to be the default option.

**Comment by aorgazf** [comment]
Hi All,
As of yesterday afternoon, the readout signal power of the module connected to qubits 0 and 1 seems to have changed.
I'm not sure why, I've checked for accidental software changes and rebooting the devices, but it remains the same.
Below is a comparison of the resonator spectroscopy for qubit 0.
image
I wonder if the issue may be related to a cable coming loose. Until we can verify this, please note that the runcard will not work well for qubits 0 and 1.

**Comment by maxhant** [comment]
> I wonder if the issue may be related to a cable coming loose.

@aorgazf all qubits are on the same feedline, so it might just be chip related if not software.

**Comment by stavros11** [comment]
> This runcard is not usable, right? Should I use the one in `alvaro/qblox9_sweepers`?

When I tried `alvaro/qblox9_sweepers` last Thursday it was working (measurement fidelity >90% for qubits 2, 3), but there were more recent pushes that I have not tested, but give a try if you have time. I believe it should be more updated than this PR.

**Comment by MatteoRobbiati** [comment]
> When I tried `alvaro/qblox9_sweepers` last Thursday it was working (measurement fidelity >90% for qubits 2, 3), but there were more recent pushes that I have not tested, but give a try if you have time. I believe it should be more updated than this PR.

I can confirm! That runcard is better than the one in this branch (but still far from usable shape).
Right now, it is not working. There is a key error related to `["repetition_duration"]` key into `settings` dict.

**Comment by stavros11** [comment]
> I can confirm! That runcard is better than the one in this branch (but still far from usable shape). Right now, it is not working. There is a key error related to `["repetition_duration"]` key into `settings` dict.

I believe some new commits were pushed in `alvaro/qblox9_sweepers` yesterday, that break compatibility at least with qibocal. Earlier today I was debugging an RB experiment for Sergi and had some issues with the result objects. I could fix these by checking out an earlier commit
```
git checkout 11f06516033b13fb9483304903a1210530f9ec39
```
but I am not sure if this will fix your error. If it does not, I would suggest contacting @aorgazf directly.

**Comment by aorgazf** [comment]
@MatteoRobbiati @scarrazza  I have pushed the latest calibration, it should work now.

**Comment by aorgazf** [comment]
Hi, I've accidentally pushed commits to this branch. I close this PR and open a new one

**Pull request closed without merging**
