### PR TITLE
Update doc

### LINKED ISSUE #457: Outdated documentation
From the last documentation deployment, you can see various warning and errors related to outdated components (new results, abstrac platform...)

https://github.com/qiboteam/qibolab/actions/runs/5109472801/jobs/9184821662#step:6:210

We should fix them, but also we may want to fix the workflow so that it fails when these kind of errors present (?)

### PR DESCRIPTION
**Pull request by rodolfocarobene**
Fixes #457.

There are still some errors mainly related to unexpected indentations

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
[Documentation tests](https://github.com/qiboteam/qibolab/actions/runs/5118742418/jobs/9203123332?pr=458#step:12:151)  are failing because `create_dummy` does not find the dummy runcard... 
Not sure why, but maybe we could just remove this "tests"?  It's a bit cheating...

**Comment by scarrazza** [comment]
I would suggest to wait for @andrea-pasquale conversion from yaml to dict.

**Comment by andrea-pasquale** [comment]
> I would suggest to wait for @andrea-pasquale conversion from yaml to dict.

I've opened a PR just now #460.
@rodolfocarobene you could try to merge locally #460 with this branch to see if it works.

**Comment by rodolfocarobene** [comment]
> I've opened a PR just now #460. @rodolfocarobene you could try to merge locally #460 with this branch to see if it works.

It's still complaining 
```
platform = create_dummy("dummy")
      File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 568, in create_dummy
        platform = Platform("dummy", runcard, [instrument], channels)
      File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 59, in __init__
        self.reload_settings()
      File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 75, in reload_settings
        with open(self.runcard) as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'dummy'
```

**Comment by andrea-pasquale** [comment]
> > I've opened a PR just now #460. @rodolfocarobene you could try to merge locally #460 with this branch to see if it works.
> 
> It's still complaining
> 
> ```
> platform = create_dummy("dummy")
>       File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 568, in create_dummy
>         platform = Platform("dummy", runcard, [instrument], channels)
>       File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 59, in __init__
>         self.reload_settings()
>       File "/home/rodolfoc/venv/qibo/qibolab/src/qibolab/platform.py", line 75, in reload_settings
>         with open(self.runcard) as file:
>     FileNotFoundError: [Errno 2] No such file or directory: 'dummy'
> ```

I tried now and it seems to work.
Could you try again? I can also push directly the merge here.

**Comment by andrea-pasquale** [comment]
> I still see no changes... Documentation itself (built with `make -C doc html`) is ok, but documentation tests (executed with `make -C doc doctest` fails)

My bad I was only generating the documentation :(
I will have a look now.

**Comment by rodolfocarobene** [comment]
@andrea-pasquale in my opinion this PR and the dummy one can be merged

**Comment by andrea-pasquale** [comment]
Sure @rodolfocarobene.
I also think that this is ready to merge.
For #460 I will wait for the qibo meeting before merging.

**Pull request merged**
