### PR TITLE
Updating qibo version

### PR DESCRIPTION
**Pull request by scarrazza**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by rodolfocarobene — APPROVED** [review]
Did we really loose compatibility with the older version of qibo?
Anyway, even if we just want to "force" people to more update versions, it's ok for me

**Comment by scarrazza** [comment]
With #541 maybe, the point here is to support 0.2.0, otherwise pip will fail.

**Review by stavros11 — APPROVED** [review]
I don't think we lose general compatibility, even after #541, but compiling the `Align` gate for sure will require the latest qibo. Anyway, it is also fine for me to force the latest version since this is used by tests.

**Comment by scarrazza** [comment]
Thanks, let's proceed them.

**Pull request merged**
