### PR TITLE
Fix RFSoC QPU tests

### PR DESCRIPTION
**Pull request by stavros11**
QPU tests are passing with QM (qw25q), qblox (qw5q_gold) and now RFSoC (on tii1q_b1):
```sh
srun -p tii1q_b1 pytest -m qpu --no-cov --platform tii1q_b1
```
(requires the `QIBOLAB_PLATFORMS` environment variable properly set)

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
Thanks @stavros11! I know tests should be passing, but I obtain this:

``` bash
(qiboenv) rodolfo.carobene@saadiyat:~/qibo/qibolab$ srun -p tii1q_b1 pytest -m qpu --no-cov --platform tii1q_b1
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.4.0, pluggy-1.2.0
rootdir: /nfs/users/rodolfo.carobene/qibo/qibolab
configfile: pyproject.toml
testpaths: tests/
plugins: mock-3.11.1, cov-4.1.0, dash-2.11.1, env-0.8.2
collected 2265 items / 2202 deselected / 63 selected

tests/test_backends.py EEEEEEEEEEEEE                                     [ 20%]
tests/test_instruments_erasynth.py EEE                                   [ 25%]
tests/test_instruments_qblox_cluster.py EEEE                             [ 31%]
tests/test_instruments_qblox_cluster_qcm_bb.py EEEEE                     [ 39%]
tests/test_instruments_qblox_cluster_qcm_rf.py EEEEE                     [ 47%]
tests/test_instruments_qblox_cluster_qrm_rf.py EEEEE                     [ 55%]
tests/test_instruments_qutech.py EEE                                     [ 60%]
tests/test_instruments_rfsoc.py EEEEE                                    [ 68%]
tests/test_instruments_rohde_schwarz.py EEEE                             [ 74%]
tests/test_instruments_zhinst.py EEE                                     [ 79%]
tests/test_platform.py EEEEEEEEEEEEE                                     [100%]
```

I suppose I am doing something wrong...

**Comment by stavros11** [comment]
Can you post what the error is because it is not visible in this message? One requirement is that the `QIBOLAB_PLATFORMS` environment variable is pointing to the folder that contains the tii1q_b1 create+runcard but I assume this is already the case.

**Comment by rodolfocarobene** [comment]
It was complaining for `adc_trig_offset` parameter in the settings section of the runcard... I have remove it and now the majority of errors are fixed.

I still get two failing tests because of the maximum length pulse:
```
    @pytest.mark.qpu
    def test_platform_execute_one_extralong_drive_pulse(qpu_platform):
        # Extra Long duration
        platform = qpu_platform
        qubit = next(iter(platform.qubits))
        sequence = PulseSequence()
        sequence.add(platform.create_qubit_drive_pulse(qubit, start=0, duration=2 * 8192 + 200))
        options = ExecutionParameters(nshots=nshots)
        if find_instrument(platform, QbloxController) is not None:
            with pytest.raises(NotImplementedError):
                platform.execute_pulse_sequence(sequence, options)
        elif find_instrument(platform, RFSoC) is not None:
            with pytest.raises(RuntimeError):
>               platform.execute_pulse_sequence(sequence, options)
E               Failed: DID NOT RAISE <class 'RuntimeError'>

```

**Comment by stavros11** [comment]
> It was complaining for `adc_trig_offset` parameter in the settings section of the runcard... I have remove it and now the majority of errors are fixed.

Are you using a different runcard? I am using the [tii1q_b1 runcard](https://github.com/qiboteam/qibolab_platforms_qrc/blob/main/tii1q_b1.yml) from qibolab_platforms_qrc main and qibosoq main and I get
```
25 passed, 32 skipped, 2202 deselected, 3 xfailed, 3 xpassed, 8 warnings
```
But this runcard doesn't seem to have any `adc_trig_offset` parameter.

> I still get two failing tests because of the maximum length pulse:
> 
> ```
>     @pytest.mark.qpu
>     def test_platform_execute_one_extralong_drive_pulse(qpu_platform):
>         # Extra Long duration
>         platform = qpu_platform
>         qubit = next(iter(platform.qubits))
>         sequence = PulseSequence()
>         sequence.add(platform.create_qubit_drive_pulse(qubit, start=0, duration=2 * 8192 + 200))
>         options = ExecutionParameters(nshots=nshots)
>         if find_instrument(platform, QbloxController) is not None:
>             with pytest.raises(NotImplementedError):
>                 platform.execute_pulse_sequence(sequence, options)
>         elif find_instrument(platform, RFSoC) is not None:
>             with pytest.raises(RuntimeError):
> >               platform.execute_pulse_sequence(sequence, options)
> E               Failed: DID NOT RAISE <class 'RuntimeError'>
> ```

This is the test that was giving me `RuntimeError` because the pulse was very long. So for you it works?

**Comment by rodolfocarobene** [comment]
Found the problem. Indeed I was using a different runcard and, in particular, this runcard was using only rectangular pulses that do not have the same limitation of gaussians

**Comment by rodolfocarobene** [comment]
But it's a bit of a problem that the test could fail or not depending on the runcard parameters... I would fix the shape maybe

**Comment by stavros11** [comment]
So the length limitation is only for non-rectangular pulses? For rectangular that length can be played? If yes, then just modifying 
```py
elif find_instrument(platform, RFSoC) is not None:
```
to
```py
elif find_instrument(platform, RFSoC) is not None and not isinstance(pulse.shape, Rectangular):
```
should fix the test in all cases.

**Comment by rodolfocarobene** [comment]
Yes I think that only rectangular pulses do not have this limitation

**Review by rodolfocarobene — APPROVED** [review]
Thanks, now it works with both runcards!

**Comment by rodolfocarobene** [comment]
Should we merge this directly into rfsoc-fixes? In this way we will not have to wait for a second review...

**Comment by stavros11** [comment]
> Should we merge this directly into rfsoc-fixes? In this way we will not have to wait for a second review...

Yes, fine with me. It does not change anything in the source code anyway so it should not affect real executions.

**Pull request merged**
