### PR TITLE
Bug(?) in q-component of DRAG pulse

### PR DESCRIPTION
**Pull request by stavros11**
Thanks @sorewachigauyo for reporting this. It would be could if someone else can confirm this is correct because I am not 100% sure.

### CODE REVIEW

**Review by hay-k — APPROVED** [review]
Looks correct to me.

**Review by alecandido — APPROVED** [review]
I should check if this is still present in 0.2 as well.

**Comment by alecandido** [comment]
Ok, in 0.2 it was already correct
https://github.com/qiboteam/qibolab/blob/f829e8f02e54abcd1fc18de5e2d1cd1df367d0a7/src/qibolab/pulses/envelope.py#L186-L194

**Review by andrea-pasquale — APPROVED** [review]
It makes sense. I didn't notice any difference when calibrating with `main` and this branch which seems weird...

**Comment by alecandido** [comment]
> It makes sense. I didn't notice any difference when calibrating with `main` and this branch which seems weird...

In a few relevant cases, `sampling_rate` will be just 1, so it's not incredibly strange

**Pull request merged**
