### PR TITLE
Remove runcards

### PR DESCRIPTION
**Pull request by stavros11**
Contains #433 and #436.

* Merge `AbstractPlatform` and `DesignPlatform` and rename to `Platform`.
* Remove `InstrumentDesign`
* Move runcards and platform creation methods to new repository https://github.com/qiboteam/qibolab_platforms_qrc

TODO:
- [x] Update `tests_instruments_qm` and `test_instruments_rfsoc`.
- [x] How to create qblox platform.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by AleCandido — APPROVED** [review]

**Comment by stavros11** [comment]
This should be ready to merge. Here are some instructions on how to use the new layout:
1. Clone https://github.com/qiboteam/qibolab_platforms_qrc
2. Checkout the branch containing the runcard you'd like to use. Currently all runcards from qibolab main (tii1q_b1 for rfsoc, qw5q_gold for qblox, qw25q for QM and iqm5q for Zurich) are in the `connectivity` branch. If your runcard is missing or is outdated, please add the latest there and push.
3. Point the environment variable `QIBOLAB_PLATFORMS` to the directory where you cloned `qibolab_platforms_qrc`. For example if you cloned in your home directory, just do
```sh
export QIBOLAB_PLATFORMS=~/qibolab_platforms_qrc
```
Optionally, you can add this in `~/.bashrc` so that you don't need to set it every time you open a new terminal.

4. Run your script. If your script is using qibocal, please use qiboteam/qibocal#365. We are renaming some classes here (`AbstractPlatform` -> `Platform`) so qibocal main will not work.

I have tested this with QM and it works. @rodolfocarobene @Jacfomg please give a try and let us know if you agree with the new layout. The idea is to move the complexity associated with the qrc runcard management (which requires different branches, etc.) away from qibolab to keep the code development cleaner.

**Comment by rodolfocarobene** [comment]
I tried it with the zcu111 and it works fine. 
With the rfsoc4x2 it cannot be tested without a server reboot... hopefully will be one of the last.

Just a couple of question:
* what will happen to the qpu tests? I don't think that the dummy instruments will support them
* To run the tests locally I also had to export `path_to_tests/dummy_qrc`, is this intended or did I miss something?

**Comment by AleCandido** [comment]
> To run the tests locally I also had to export `path_to_tests/dummy_qrc`, is this intended or did I miss something?

This one is weird, since the env var should be provided by:
https://github.com/qiboteam/qibolab/blob/5c1561a588e3a2d2dbc62e48f98712e28657abdd/tests/conftest.py#L42-L48

> what will happen to the qpu tests? I don't think that the dummy instruments will support them

The "dummy" instruments at the moment are the actual ones, but they won't be forever, since we won't update them.
This is a good point for the selfhosted runner, for which we already planned to export the suitable variable for Saadiyat.

**Review by rodolfocarobene — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
> This should be ready to merge. Here are some instructions on how to use the new layout:
> 
> 1. Clone https://github.com/qiboteam/qibolab_platforms_qrc
> 2. Checkout the branch containing the runcard you'd like to use. Currently all runcards from qibolab main (tii1q_b1 for rfsoc, qw5q_gold for qblox, qw25q for QM and iqm5q for Zurich) are in the `connectivity` branch. If your runcard is missing or is outdated, please add the latest there and push.
> 3. Point the environment variable `QIBOLAB_PLATFORMS` to the directory where you cloned `qibolab_platforms_qrc`. For example if you cloned in your home directory, just do
> 
> ```shell
> export QIBOLAB_PLATFORMS=~/qibolab_platforms_qrc
> ```
> 
> Optionally, you can add this in `~/.bashrc` so that you don't need to set it every time you open a new terminal.
> 
> 4. Run your script. If your script is using qibocal, please use [Sync with qiboteam/qibolab#438 qibocal#365](https://github.com/qiboteam/qibocal/pull/365). We are renaming some classes here (`AbstractPlatform` -> `Platform`) so qibocal main will not work.
> 
> I have tested this with QM and it works. @rodolfocarobene @Jacfomg please give a try and let us know if you agree with the new layout. The idea is to move the complexity associated with the qrc runcard management (which requires different branches, etc.) away from qibolab to keep the code development cleaner.

Thanks @stavros11.
I give it a try with the `RFSoC` and I got an `Aborted` error?
In `main` branches everything is working as expected.
@rodolfocarobene did you test also the rfsoc or only the zcu111?

**Comment by AleCandido** [comment]
@andrea-pasquale `Aborted` is pretty weird, can you post the stack trace, if any?

**Comment by rodolfocarobene** [comment]
>  With the rfsoc4x2 it cannot be tested without a server reboot... hopefully will be one of the last.

As I was saying, the rfsoc needs a reboot. It tries to build objects like qubits from different locations (since for example the qubit object was moved) and fails.
In the log file on the board the error was more clear:
```
ERROR :: 2023-05-29 05:45:40 ::  
Traceback (most recent call last):
  File "/home/xilinx/qibosoq/src/qibosoq/rfsoc_server.py", line 78, in handle
    data = self.receive_command()
  File "/home/xilinx/qibosoq/src/qibosoq/rfsoc_server.py", line 36, in receive_command
    data = pickle.loads(received)
ModuleNotFoundError: No module named 'qibolab.qubits'

```

**Comment by andrea-pasquale** [comment]
Oh sorry I didn't read that it needs a reboot, my bad @rodolfocarobene.
@AleCandido `Aborted` could happen with the board sometime, usually it refers to an error on the server side, right @rodolfocarobene?
We could reboot the server whenever you want @rodolfocarobene. Let me know when you do it and I can update the runcard.

**Comment by AleCandido** [comment]
> @AleCandido `Aborted` could happen with the board sometime, usually it refers to an error on the server side, right @rodolfocarobene?

What I understood from the code is that:
- **before** any exception was pickled, and reraised on client side, so you should get the specific exception, not a generic `AbortedError`
- **after** pickling removal, it should raise a `RuntimeError` with a suitable description

Moreover, the only aborted error known to standard library seems to be [`ConnectionAbortedError`](https://docs.python.org/3/library/exceptions.html#ConnectionAbortedError), but it is not clear to me why it should happen.

**Comment by AleCandido** [comment]
Even sending manually a `SIGABRT` (6) to a running Python instance, I just obtain this:

```py
❯ py -c "import time; time.sleep(100)"
[1]    468442 IOT instruction (core dumped)  python3 -c "import time; time.sleep(100)"
```

**Comment by rodolfocarobene** [comment]
@andrea-pasquale The server is now on with this branch of qibolab

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale The server is now on with this branch of qibolab

Thanks @rodolfocarobene.

**Comment by Jacfomg** [comment]
Works with Zurich with the routines on main. I should try to get the branch with duration sweepers ready as well with these changes.

**Review by Jacfomg — APPROVED** [review]

**Review by Jacfomg — APPROVED** [review]

**Comment by AleCandido** [comment]
@stavros11 if @andrea-pasquale also confirms, I would merge.

**Comment by andrea-pasquale** [comment]
We can merge also for me.
Just one question. I'm recalibrating `tii1q_b1`. Where should I put the new runcard? In the new repo?

**Review by andrea-pasquale — APPROVED** [review]

**Comment by AleCandido** [comment]
> Just one question. I'm recalibrating `tii1q_b1`. Where should I put the new runcard? In the new repo?

For the time being yes, I'm working on the database.

**Comment by stavros11** [comment]
> @stavros11 if @andrea-pasquale also confirms, I would merge.

Fine with me. I would just open an issue regarding the qpu tests with labels, which I think we are breaking here. But I would postpone this until we remove the multiqubit platform, because it should be easier to refactor tests if we have only one platform.

**Pull request merged**
