### PR TITLE
Qblox review

### PR DESCRIPTION
**Pull request by rodolfocarobene**
Since #518 is quite big, in this PR we can use this PR to change/fix the review comments while still having a working PR and this to test everything.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by scarrazza** [comment]
What is the current status of this PR?

**Comment by rodolfocarobene** [comment]
> What is the current status of this PR?

This and the other PR are almost ready, we are testing them to be sure no bugs were introduced during review

**Comment by rodolfocarobene** [comment]
@andrea-pasquale , can you confirm us that this PR it's working? So that we proceed merging it into the main qblox one

**Comment by andrea-pasquale** [comment]
Yes, it is working for me. We can merge it.

**Pull request merged**
